services:
    laravel.test:
        container_name: shopping-list-laravel
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${FORWARD_APP_PORT:-8000}:80'
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            PHP_IDE_CONFIG: '${PHP_IDE_CONFIG:-}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/app'
        networks:
            - shopping-list
        depends_on:
            - mysql
    mysql:
        container_name: shopping-list-mysql
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'shopping-list-mysql:/var/lib/mysql'
        networks:
            - shopping-list
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    phpmyadmin:
        container_name: shopping-list-phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:mysql
        ports:
            - '${FORWARD_PHPMYADMIN_PORT:-8080}:80'
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: mysql
        networks:
            - shopping-list
networks:
    shopping-list:
        driver: bridge
volumes:
    shopping-list-mysql:
        driver: local
